<a href="https://colab.research.google.com/github/brukted/ml-onboarding/blob/main/Checkpoints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [4]:
import itertools
data = ['A', 'B', 'C']
list(itertools.combinations(data, 2))

[('A', 'B'), ('A', 'C'), ('B', 'C')]

**CP2**:

---


Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [16]:
import itertools
cyclic_iter = itertools.cycle(['Python', 'is', 'fun'])
[next(cyclic_iter) for _ in range(10)]

['Python', 'is', 'fun', 'Python', 'is', 'fun', 'Python', 'is', 'fun', 'Python']

**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [15]:
import glob
glob.glob("*.py")

['test.py']

**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [22]:
from bs4 import BeautifulSoup

page = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"
soup = BeautifulSoup(page, 'html.parser')

p_text = soup.find("p").text
print(p_text)

AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [23]:
import re
def replaceAiWithArtificialIntelligence(text):
  pattern = re.compile(".*AI.*")
  return pattern.sub("Artificial Intelligence", text)

replaceAiWithArtificialIntelligence(p_text)

'Artificial Intelligence'

**CP6**: Create a numpy array of 10 zeros.

In [26]:
import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**CP7** Create a numpy array of the integers from 10 to 49.

In [33]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [34]:
np.reshape(np.arange(0, 9), (3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

Machine learning models require large amounts of data to learn from. The more data that is used to train a model, the more accurate the model will be. A large dataset is one that contains millions or even billions of data points.

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

* Censoring information. AI can be used to filter out information that is considered to be harmful or objectionable. This can be used by governments or other organizations to control what information is available to the public.
* Spreading misinformation. AI can be used to generate fake
news articles, social media posts, and other forms of content that can be used to spread misinformation. This can have a negative impact on society, by sowing discord and undermining trust in institutions.

Misinformation can be prevented using detectors by identifying and removing false or misleading content. Detectors can be used to analyze text, images, and videos to identify patterns that are often associated with misinformation. By removing false or misleading content, detectors can help to create a more accurate and reliable online environment.
